/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include "../libliveshowvideoplayer/live_show_video_controller.h"
/* Header for class com_changba_songstudio_video_player_ELPlayerController */

#ifndef _Included_com_changba_songstudio_video_player_ELPlayerController
#define _Included_com_changba_songstudio_video_player_ELPlayerController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    onSurfaceCreated
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_onSurfaceCreated
  (JNIEnv *, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    onSurfaceDestroyed
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_onSurfaceDestroyed
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    prepare
 * Signature: (Ljava/lang/String;[IIIFF)Z
 */
JNIEXPORT jint JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_prepare
  (JNIEnv *, jobject, jstring, jstring, jintArray, jint, jint, jboolean, jfloat, jfloat);
JNIEXPORT jint JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_retry
  (JNIEnv *, jobject, jint, jstring, jintArray, jint, jint, jboolean, jfloat, jfloat);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_pause
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_play
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_stop
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    getBufferedProgress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_getBufferedProgress
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    getPlayProgress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_getPlayProgress
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    seekToPosition
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_seekToPosition
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    resetRenderSize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_resetRenderSize
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_changba_songstudio_video_player_ELPlayerController
 * Method:    setRTMPCurl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_setRTMPCurl
  (JNIEnv *, jobject, jint, jstring);

JNIEXPORT jstring JNICALL Java_com_changba_songstudio_video_player_ELPlayerController_getBuriedPoints
  (JNIEnv * env, jobject obj);
#ifdef __cplusplus
}
#endif
#endif
