package com.tencent.audiochanneldemo.player;

public interface PlayerException {

    int EXCEPTION_TYPE_MALFORMED = 50;
    int EXCEPTION_TYPE_IO = 51;
    int EXCEPTION_TYPE_NULLPOINTER = 52;

    int EXCEPTION_TYPE_FILENOTFOUND = 53;
    int EXCEPTION_TYPE_FILECANNOTREAD = 54;
    int EXCEPTION_TYPE_UNKNOWFORMAT = 55;
    int EXCEPTION_TYPE_UNSUPPORTMETHOD = 56;
    int EXCEPTION_TYPE_THIRDOUTPUT = 57;
    int EXCEPTION_TYPE_INIT_EXCEPTION = 58;

    int EXCEPTION_TYPE_LOADLIB = 60;
    int EXCEPTION_TYPE_INITLIB = 61;
    int EXCEPTION_TYPE_NATIVEOPEN = 62;
    int EXCEPTION_TYPE_GETAUDIOINFO = 63;
    int EXCEPTION_TYPE_INVALIDAUDIOINFO = 64;
    int EXCEPTION_TYPE_UNSUPPORTAUDIOINFO = 65;
    int EXCEPTION_TYPE_CREATAUDIOTRACK = 66;
    int EXCEPTION_TYPE_DECODE = 67;
    int EXCEPTION_TYPE_PLAYAUDIOTRACK = 68;
    int EXCEPTION_TYPE_RESOURCE_LOAD_TOO_SLOW = 69; // 资源加载太慢，一般指网络

    int EXCEPTION_TYPE_INVALIDSTART = 71;
    int EXCEPTION_TYPE_INVALIDPAUSE = 72;
    int EXCEPTION_TYPE_INVALIDSTOP = 73;
    int EXCEPTION_TYPE_INVALIDSEEK = 74;
    int EXCEPTION_TYPE_INVALIDRESET = 75;
    int EXCEPTION_TYPE_INVALIDRELEASE = 76;
    int EXCEPTION_TYPE_INVALIDSETAUDIOEFFECT = 77;
    int EXCEPTION_TYPE_INVALIDGETDURATION = 78;
    int EXCEPTION_TYPE_INVALIDGETPOSITION = 79;
    int EXCEPTION_TYPE_INVALIDSETVOLUME = 80;


    int EXCEPTION_IN_SETDATASOURCE = 90;
    int EXCEPTION_IN_PREPARE = 91;
    int EXCEPTION_IN_START = 92;
    int EXCEPTION_IN_PAUSE = 93;
    int EXCEPTION_IN_STOP = 94;
    int EXCEPTION_IN_SEEK = 95;
    int EXCEPTION_IN_SETAUDIOEFFECT = 96;
    int EXCEPTION_IN_RELEASE = 97;
    int EXCEPTION_IN_RESET = 98;
    int EXCEPTION_IN_BASEMETHOD = 99;

}
